2022-05-17 15:25:48,397 - INFO - ###########################################
2022-05-17 15:25:48,397 - INFO - /home/php/Documents/Thierry/OTAnalysis/data_test/verif/b1c1-2021.06.02-11.46.00.099.jpk-nt-force
2022-05-17 15:25:48,398 - INFO - ###########################################
2022-05-17 15:25:48,399 - ERROR - 'automatic_type'
2022-05-17 15:25:48,399 - ERROR - Traceback (most recent call last):
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/controller/controller.py", line 226, in create_dict_curves
    error = new_curve.analyzed_curve(
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 1014, in analyzed_curve
    type_curve = self.curve_return_analyze(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 812, in curve_return_analyze
    type_curve = self.classification(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 958, in classification
    if self.features['automatic_type'] == "NAD":
KeyError: 'automatic_type'

2022-05-17 15:25:48,399 - INFO - ###########################################
2022-05-17 15:25:48,662 - INFO - ###########################################
2022-05-17 15:25:48,662 - INFO - /home/php/Documents/Thierry/OTAnalysis/data_test/test/b3c3-2021.06.07-14.50.58.217.jpk-nt-force
2022-05-17 15:25:48,662 - INFO - ###########################################
2022-05-17 15:25:48,662 - ERROR - 'automatic_type'
2022-05-17 15:25:48,662 - ERROR - Traceback (most recent call last):
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/controller/controller.py", line 226, in create_dict_curves
    error = new_curve.analyzed_curve(
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 1014, in analyzed_curve
    type_curve = self.curve_return_analyze(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 812, in curve_return_analyze
    type_curve = self.classification(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 958, in classification
    if self.features['automatic_type'] == "NAD":
KeyError: 'automatic_type'

2022-05-17 15:25:48,662 - INFO - ###########################################
2022-05-17 15:25:49,254 - INFO - ###########################################
2022-05-17 15:25:49,254 - INFO - /home/php/Documents/Thierry/OTAnalysis/data_test/test/b3c3-2021.06.07-14.58.15.777.jpk-nt-force
2022-05-17 15:25:49,254 - INFO - ###########################################
2022-05-17 15:25:49,254 - ERROR - 'automatic_type'
2022-05-17 15:25:49,254 - ERROR - Traceback (most recent call last):
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/controller/controller.py", line 226, in create_dict_curves
    error = new_curve.analyzed_curve(
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 1014, in analyzed_curve
    type_curve = self.curve_return_analyze(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 812, in curve_return_analyze
    type_curve = self.classification(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 958, in classification
    if self.features['automatic_type'] == "NAD":
KeyError: 'automatic_type'

2022-05-17 15:25:49,254 - INFO - ###########################################
2022-05-17 15:25:49,533 - INFO - ###########################################
2022-05-17 15:25:49,533 - INFO - /home/php/Documents/Thierry/OTAnalysis/data_test/test/b3c3-2021.06.07-14.52.58.631.jpk-nt-force
2022-05-17 15:25:49,533 - INFO - ###########################################
2022-05-17 15:25:49,534 - ERROR - 'automatic_type'
2022-05-17 15:25:49,534 - ERROR - Traceback (most recent call last):
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/controller/controller.py", line 226, in create_dict_curves
    error = new_curve.analyzed_curve(
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 1014, in analyzed_curve
    type_curve = self.curve_return_analyze(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 812, in curve_return_analyze
    type_curve = self.classification(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 958, in classification
    if self.features['automatic_type'] == "NAD":
KeyError: 'automatic_type'

2022-05-17 15:25:49,534 - INFO - ###########################################
2022-05-17 15:25:49,827 - INFO - ###########################################
2022-05-17 15:25:49,827 - INFO - /home/php/Documents/Thierry/OTAnalysis/data_test/test/b7c7-2021.06.07-15.31.44.019.jpk-nt-force
2022-05-17 15:25:49,827 - INFO - ###########################################
2022-05-17 15:25:49,828 - ERROR - 'automatic_type'
2022-05-17 15:25:49,828 - ERROR - Traceback (most recent call last):
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/controller/controller.py", line 226, in create_dict_curves
    error = new_curve.analyzed_curve(
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 1014, in analyzed_curve
    type_curve = self.curve_return_analyze(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 812, in curve_return_analyze
    type_curve = self.classification(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 958, in classification
    if self.features['automatic_type'] == "NAD":
KeyError: 'automatic_type'

2022-05-17 15:25:49,828 - INFO - ###########################################
2022-05-17 15:25:50,108 - INFO - ###########################################
2022-05-17 15:25:50,108 - INFO - /home/php/Documents/Thierry/OTAnalysis/data_test/test/b3c3-2021.06.07-14.57.55.683.jpk-nt-force
2022-05-17 15:25:50,108 - INFO - ###########################################
2022-05-17 15:25:50,108 - ERROR - 'automatic_type'
2022-05-17 15:25:50,109 - ERROR - Traceback (most recent call last):
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/controller/controller.py", line 226, in create_dict_curves
    error = new_curve.analyzed_curve(
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 1014, in analyzed_curve
    type_curve = self.curve_return_analyze(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 812, in curve_return_analyze
    type_curve = self.classification(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 958, in classification
    if self.features['automatic_type'] == "NAD":
KeyError: 'automatic_type'

2022-05-17 15:25:50,109 - INFO - ###########################################
2022-05-17 15:25:50,428 - INFO - ###########################################
2022-05-17 15:25:50,428 - INFO - /home/php/Documents/Thierry/OTAnalysis/data_test/test/b1c1gg-2021.06.02-15.30.30.294.txt
2022-05-17 15:25:50,429 - INFO - ###########################################
2022-05-17 15:25:50,429 - ERROR - 'automatic_type'
2022-05-17 15:25:50,429 - ERROR - Traceback (most recent call last):
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/controller/controller.py", line 226, in create_dict_curves
    error = new_curve.analyzed_curve(
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 1014, in analyzed_curve
    type_curve = self.curve_return_analyze(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 812, in curve_return_analyze
    type_curve = self.classification(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 958, in classification
    if self.features['automatic_type'] == "NAD":
KeyError: 'automatic_type'

2022-05-17 15:25:50,429 - INFO - ###########################################
2022-05-17 15:25:50,697 - INFO - ###########################################
2022-05-17 15:25:50,698 - INFO - /home/php/Documents/Thierry/OTAnalysis/data_test/test/b3c3-2021.06.07-14.58.55.908.jpk-nt-force
2022-05-17 15:25:50,698 - INFO - ###########################################
2022-05-17 15:25:50,698 - ERROR - 'automatic_type'
2022-05-17 15:25:50,698 - ERROR - Traceback (most recent call last):
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/controller/controller.py", line 226, in create_dict_curves
    error = new_curve.analyzed_curve(
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 1014, in analyzed_curve
    type_curve = self.curve_return_analyze(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 812, in curve_return_analyze
    type_curve = self.classification(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 958, in classification
    if self.features['automatic_type'] == "NAD":
KeyError: 'automatic_type'

2022-05-17 15:25:50,698 - INFO - ###########################################
2022-05-17 15:25:50,870 - INFO - ###########################################
2022-05-17 15:25:50,870 - INFO - /home/php/Documents/Thierry/OTAnalysis/data_test/test/b1c1-2021.06.02-15.30.30.294.jpk-nt-force
2022-05-17 15:25:50,870 - INFO - ###########################################
2022-05-17 15:25:50,870 - ERROR - 'automatic_type'
2022-05-17 15:25:50,871 - ERROR - Traceback (most recent call last):
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/controller/controller.py", line 226, in create_dict_curves
    error = new_curve.analyzed_curve(
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 1014, in analyzed_curve
    type_curve = self.curve_return_analyze(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 812, in curve_return_analyze
    type_curve = self.classification(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 958, in classification
    if self.features['automatic_type'] == "NAD":
KeyError: 'automatic_type'

2022-05-17 15:25:50,871 - INFO - ###########################################
2022-05-17 15:25:51,157 - INFO - ###########################################
2022-05-17 15:25:51,157 - INFO - /home/php/Documents/Thierry/OTAnalysis/data_test/test/b4c4-2021.06.07-15.05.45.485.jpk-nt-force
2022-05-17 15:25:51,158 - INFO - ###########################################
2022-05-17 15:25:51,158 - ERROR - 'automatic_type'
2022-05-17 15:25:51,158 - ERROR - Traceback (most recent call last):
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/controller/controller.py", line 226, in create_dict_curves
    error = new_curve.analyzed_curve(
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 1014, in analyzed_curve
    type_curve = self.curve_return_analyze(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 812, in curve_return_analyze
    type_curve = self.classification(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 958, in classification
    if self.features['automatic_type'] == "NAD":
KeyError: 'automatic_type'

2022-05-17 15:25:51,158 - INFO - ###########################################
2022-05-17 15:25:51,397 - INFO - ###########################################
2022-05-17 15:25:51,397 - INFO - /home/php/Documents/Thierry/OTAnalysis/data_test/test/b2c2-2021.06.07-14.37.36.051.jpk-nt-force
2022-05-17 15:25:51,397 - INFO - ###########################################
2022-05-17 15:25:51,398 - ERROR - 'automatic_type'
2022-05-17 15:25:51,398 - ERROR - Traceback (most recent call last):
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/controller/controller.py", line 226, in create_dict_curves
    error = new_curve.analyzed_curve(
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 1014, in analyzed_curve
    type_curve = self.curve_return_analyze(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 812, in curve_return_analyze
    type_curve = self.classification(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 958, in classification
    if self.features['automatic_type'] == "NAD":
KeyError: 'automatic_type'

2022-05-17 15:25:51,398 - INFO - ###########################################
2022-05-17 15:25:51,533 - INFO - ###########################################
2022-05-17 15:25:51,533 - INFO - /home/php/Documents/Thierry/OTAnalysis/data_test/test/b4c4-2021.06.07-15.04.04.912.jpk-nt-force
2022-05-17 15:25:51,533 - INFO - ###########################################
2022-05-17 15:25:51,534 - ERROR - 'automatic_type'
2022-05-17 15:25:51,534 - ERROR - Traceback (most recent call last):
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/controller/controller.py", line 226, in create_dict_curves
    error = new_curve.analyzed_curve(
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 1014, in analyzed_curve
    type_curve = self.curve_return_analyze(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 812, in curve_return_analyze
    type_curve = self.classification(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 958, in classification
    if self.features['automatic_type'] == "NAD":
KeyError: 'automatic_type'

2022-05-17 15:25:51,534 - INFO - ###########################################
2022-05-17 15:25:51,824 - INFO - ###########################################
2022-05-17 15:25:51,824 - INFO - /home/php/Documents/Thierry/OTAnalysis/data_test/test/b3c3-2021.06.07-14.52.38.561.jpk-nt-force
2022-05-17 15:25:51,824 - INFO - ###########################################
2022-05-17 15:25:51,825 - ERROR - 'automatic_type'
2022-05-17 15:25:51,825 - ERROR - Traceback (most recent call last):
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/controller/controller.py", line 226, in create_dict_curves
    error = new_curve.analyzed_curve(
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 1014, in analyzed_curve
    type_curve = self.curve_return_analyze(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 812, in curve_return_analyze
    type_curve = self.classification(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 958, in classification
    if self.features['automatic_type'] == "NAD":
KeyError: 'automatic_type'

2022-05-17 15:25:51,825 - INFO - ###########################################
2022-05-17 15:25:52,143 - INFO - ###########################################
2022-05-17 15:25:52,143 - INFO - /home/php/Documents/Thierry/OTAnalysis/data_test/test/b1c1-2021.06.07-14.28.30.039.jpk-nt-force
2022-05-17 15:25:52,143 - INFO - ###########################################
2022-05-17 15:25:52,143 - ERROR - 'automatic_type'
2022-05-17 15:25:52,143 - ERROR - Traceback (most recent call last):
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/controller/controller.py", line 226, in create_dict_curves
    error = new_curve.analyzed_curve(
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 1014, in analyzed_curve
    type_curve = self.curve_return_analyze(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 812, in curve_return_analyze
    type_curve = self.classification(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 958, in classification
    if self.features['automatic_type'] == "NAD":
KeyError: 'automatic_type'

2022-05-17 15:25:52,144 - INFO - ###########################################
2022-05-17 15:25:52,421 - INFO - ###########################################
2022-05-17 15:25:52,421 - INFO - /home/php/Documents/Thierry/OTAnalysis/data_test/test/b3c3-2021.06.07-15.00.15.683.jpk-nt-force
2022-05-17 15:25:52,421 - INFO - ###########################################
2022-05-17 15:25:52,421 - ERROR - 'automatic_type'
2022-05-17 15:25:52,422 - ERROR - Traceback (most recent call last):
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/controller/controller.py", line 226, in create_dict_curves
    error = new_curve.analyzed_curve(
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 1014, in analyzed_curve
    type_curve = self.curve_return_analyze(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 812, in curve_return_analyze
    type_curve = self.classification(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 958, in classification
    if self.features['automatic_type'] == "NAD":
KeyError: 'automatic_type'

2022-05-17 15:25:52,422 - INFO - ###########################################
2022-05-17 15:25:52,713 - INFO - ###########################################
2022-05-17 15:25:52,713 - INFO - /home/php/Documents/Thierry/OTAnalysis/data_test/test/b6c6-2021.06.07-15.20.55.095.jpk-nt-force
2022-05-17 15:25:52,713 - INFO - ###########################################
2022-05-17 15:25:52,713 - ERROR - 'automatic_type'
2022-05-17 15:25:52,713 - ERROR - Traceback (most recent call last):
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/controller/controller.py", line 226, in create_dict_curves
    error = new_curve.analyzed_curve(
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 1014, in analyzed_curve
    type_curve = self.curve_return_analyze(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 812, in curve_return_analyze
    type_curve = self.classification(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 958, in classification
    if self.features['automatic_type'] == "NAD":
KeyError: 'automatic_type'

2022-05-17 15:25:52,713 - INFO - ###########################################
2022-05-17 15:25:52,988 - INFO - ###########################################
2022-05-17 15:25:52,988 - INFO - /home/php/Documents/Thierry/OTAnalysis/data_test/test/b7c7-2021.06.07-15.32.44.493.jpk-nt-force
2022-05-17 15:25:52,989 - INFO - ###########################################
2022-05-17 15:25:52,989 - ERROR - 'automatic_type'
2022-05-17 15:25:52,989 - ERROR - Traceback (most recent call last):
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/controller/controller.py", line 226, in create_dict_curves
    error = new_curve.analyzed_curve(
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 1014, in analyzed_curve
    type_curve = self.curve_return_analyze(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 812, in curve_return_analyze
    type_curve = self.classification(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 958, in classification
    if self.features['automatic_type'] == "NAD":
KeyError: 'automatic_type'

2022-05-17 15:25:52,989 - INFO - ###########################################
2022-05-17 15:25:53,273 - INFO - ###########################################
2022-05-17 15:25:53,273 - INFO - /home/php/Documents/Thierry/OTAnalysis/data_test/test/b3c3-2021.06.07-14.56.40.932.jpk-nt-force
2022-05-17 15:25:53,273 - INFO - ###########################################
2022-05-17 15:25:53,274 - ERROR - 'automatic_type'
2022-05-17 15:25:53,274 - ERROR - Traceback (most recent call last):
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/controller/controller.py", line 226, in create_dict_curves
    error = new_curve.analyzed_curve(
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 1014, in analyzed_curve
    type_curve = self.curve_return_analyze(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 812, in curve_return_analyze
    type_curve = self.classification(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 958, in classification
    if self.features['automatic_type'] == "NAD":
KeyError: 'automatic_type'

2022-05-17 15:25:53,274 - INFO - ###########################################
2022-05-17 15:25:53,444 - INFO - ###########################################
2022-05-17 15:25:53,444 - INFO - /home/php/Documents/Thierry/OTAnalysis/data_test/test/b1c1-2021.06.07-14.34.00.774.jpk-nt-force
2022-05-17 15:25:53,444 - INFO - ###########################################
2022-05-17 15:25:53,445 - ERROR - 'automatic_type'
2022-05-17 15:25:53,445 - ERROR - Traceback (most recent call last):
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/controller/controller.py", line 226, in create_dict_curves
    error = new_curve.analyzed_curve(
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 1014, in analyzed_curve
    type_curve = self.curve_return_analyze(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 812, in curve_return_analyze
    type_curve = self.classification(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 958, in classification
    if self.features['automatic_type'] == "NAD":
KeyError: 'automatic_type'

2022-05-17 15:25:53,445 - INFO - ###########################################
2022-05-17 15:25:53,724 - INFO - ###########################################
2022-05-17 15:25:53,724 - INFO - /home/php/Documents/Thierry/OTAnalysis/data_test/test/b3c3-2021.06.07-15.00.35.722.jpk-nt-force
2022-05-17 15:25:53,724 - INFO - ###########################################
2022-05-17 15:25:53,725 - ERROR - 'automatic_type'
2022-05-17 15:25:53,725 - ERROR - Traceback (most recent call last):
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/controller/controller.py", line 226, in create_dict_curves
    error = new_curve.analyzed_curve(
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 1014, in analyzed_curve
    type_curve = self.curve_return_analyze(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 812, in curve_return_analyze
    type_curve = self.classification(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 958, in classification
    if self.features['automatic_type'] == "NAD":
KeyError: 'automatic_type'

2022-05-17 15:25:53,725 - INFO - ###########################################
2022-05-17 15:25:54,011 - INFO - ###########################################
2022-05-17 15:25:54,011 - INFO - /home/php/Documents/Thierry/OTAnalysis/data_test/test/b7c7-2021.06.07-15.33.44.786.jpk-nt-force
2022-05-17 15:25:54,011 - INFO - ###########################################
2022-05-17 15:25:54,012 - ERROR - 'automatic_type'
2022-05-17 15:25:54,012 - ERROR - Traceback (most recent call last):
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/controller/controller.py", line 226, in create_dict_curves
    error = new_curve.analyzed_curve(
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 1014, in analyzed_curve
    type_curve = self.curve_return_analyze(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 812, in curve_return_analyze
    type_curve = self.classification(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 958, in classification
    if self.features['automatic_type'] == "NAD":
KeyError: 'automatic_type'

2022-05-17 15:25:54,012 - INFO - ###########################################
2022-05-17 15:25:54,354 - INFO - ###########################################
2022-05-17 15:25:54,354 - INFO - /home/php/Documents/Thierry/OTAnalysis/data_test/test/b3c3-2021.06.07-14.58.35.877.jpk-nt-force
2022-05-17 15:25:54,354 - INFO - ###########################################
2022-05-17 15:25:54,355 - ERROR - 'automatic_type'
2022-05-17 15:25:54,355 - ERROR - Traceback (most recent call last):
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/controller/controller.py", line 226, in create_dict_curves
    error = new_curve.analyzed_curve(
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 1014, in analyzed_curve
    type_curve = self.curve_return_analyze(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 812, in curve_return_analyze
    type_curve = self.classification(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 958, in classification
    if self.features['automatic_type'] == "NAD":
KeyError: 'automatic_type'

2022-05-17 15:25:54,355 - INFO - ###########################################
2022-05-17 15:25:54,599 - INFO - ###########################################
2022-05-17 15:25:54,599 - INFO - /home/php/Documents/Thierry/OTAnalysis/data_test/jpk_nt_force/b3c3-2021.06.07-14.50.58.217.jpk-nt-force
2022-05-17 15:25:54,599 - INFO - ###########################################
2022-05-17 15:25:54,600 - ERROR - 'automatic_type'
2022-05-17 15:25:54,600 - ERROR - Traceback (most recent call last):
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/controller/controller.py", line 226, in create_dict_curves
    error = new_curve.analyzed_curve(
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 1014, in analyzed_curve
    type_curve = self.curve_return_analyze(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 812, in curve_return_analyze
    type_curve = self.classification(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 958, in classification
    if self.features['automatic_type'] == "NAD":
KeyError: 'automatic_type'

2022-05-17 15:25:54,600 - INFO - ###########################################
2022-05-17 15:25:54,899 - INFO - ###########################################
2022-05-17 15:25:54,899 - INFO - /home/php/Documents/Thierry/OTAnalysis/data_test/txt/b2c2g-2021.06.04-15.26.42.925.txt
2022-05-17 15:25:54,899 - INFO - ###########################################
2022-05-17 15:25:54,900 - ERROR - 'automatic_type'
2022-05-17 15:25:54,900 - ERROR - Traceback (most recent call last):
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/controller/controller.py", line 226, in create_dict_curves
    error = new_curve.analyzed_curve(
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 1014, in analyzed_curve
    type_curve = self.curve_return_analyze(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 812, in curve_return_analyze
    type_curve = self.classification(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 958, in classification
    if self.features['automatic_type'] == "NAD":
KeyError: 'automatic_type'

2022-05-17 15:25:54,900 - INFO - ###########################################
2022-05-17 15:25:55,213 - INFO - ###########################################
2022-05-17 15:25:55,213 - INFO - /home/php/Documents/Thierry/OTAnalysis/data_test/txt/b1c1gg-2021.06.02-15.34.26.234.txt
2022-05-17 15:25:55,213 - INFO - ###########################################
2022-05-17 15:25:55,214 - ERROR - 'automatic_type'
2022-05-17 15:25:55,214 - ERROR - Traceback (most recent call last):
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/controller/controller.py", line 226, in create_dict_curves
    error = new_curve.analyzed_curve(
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 1014, in analyzed_curve
    type_curve = self.curve_return_analyze(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 812, in curve_return_analyze
    type_curve = self.classification(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 958, in classification
    if self.features['automatic_type'] == "NAD":
KeyError: 'automatic_type'

2022-05-17 15:25:55,214 - INFO - ###########################################
2022-05-17 15:25:55,515 - INFO - ###########################################
2022-05-17 15:25:55,515 - INFO - /home/php/Documents/Thierry/OTAnalysis/data_test/txt/b1c1gg-2021.06.02-15.32.23.111.txt
2022-05-17 15:25:55,515 - INFO - ###########################################
2022-05-17 15:25:55,516 - ERROR - 'automatic_type'
2022-05-17 15:25:55,516 - ERROR - Traceback (most recent call last):
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/controller/controller.py", line 226, in create_dict_curves
    error = new_curve.analyzed_curve(
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 1014, in analyzed_curve
    type_curve = self.curve_return_analyze(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 812, in curve_return_analyze
    type_curve = self.classification(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 958, in classification
    if self.features['automatic_type'] == "NAD":
KeyError: 'automatic_type'

2022-05-17 15:25:55,516 - INFO - ###########################################
2022-05-17 15:25:55,826 - INFO - ###########################################
2022-05-17 15:25:55,826 - INFO - /home/php/Documents/Thierry/OTAnalysis/data_test/txt/b1c1gg-2021.06.02-15.34.06.018.txt
2022-05-17 15:25:55,826 - INFO - ###########################################
2022-05-17 15:25:55,826 - ERROR - 'automatic_type'
2022-05-17 15:25:55,827 - ERROR - Traceback (most recent call last):
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/controller/controller.py", line 226, in create_dict_curves
    error = new_curve.analyzed_curve(
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 1014, in analyzed_curve
    type_curve = self.curve_return_analyze(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 812, in curve_return_analyze
    type_curve = self.classification(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 958, in classification
    if self.features['automatic_type'] == "NAD":
KeyError: 'automatic_type'

2022-05-17 15:25:55,827 - INFO - ###########################################
